---
version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: always
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pi-hole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "443:443/tcp"
    volumes:
      - '/root/docker/pihole/etc-pihole/:/etc/pihole/'
      - '/root/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    environment:
      TZ: Europe/Madrid
      INTERFACE: eth0
      VIRTUAL_HOST: pihole
      ServerIP: 10.0.0.3
      DNS1: 10.0.0.2#5054
      DNS2: ''
      DNSMASQ_LISTENING: all
      IPv6: 'false'
      WEBPASSWORD: YOUR_PASSWD
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
